/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ContaBancaria;

/**
 *
 * @author Caio Moreira Cancela
 */
public class Janela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Janela.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public Janela() {
        initComponents();
        getContentPane().setLayout(null);
        configurarBounds();
        setSize(400, 255);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgContas = new javax.swing.ButtonGroup();
        jlAgencia = new javax.swing.JLabel();
        jtfAgencia = new javax.swing.JTextField();
        jlConta = new javax.swing.JLabel();
        jtfConta = new javax.swing.JTextField();
        jSeparator01 = new javax.swing.JSeparator();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        jrbCorrente = new javax.swing.JRadioButton();
        jrbPoupanca = new javax.swing.JRadioButton();
        jSeparator02 = new javax.swing.JSeparator();
        jbConsultar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laboratório de Programação");
        setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 255));

        jlAgencia.setText("Código da Agência:");

        jtfAgencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jlConta.setText("Número da Conta:");

        jtfConta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlNome.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jlEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlEndereco.setText("Endereço:");

        jtfTelefone.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jlTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTelefone.setText("Telefone:");

        jtfEndereco.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jtfCpf.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jlCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCpf.setText("CPF:");

        bgContas.add(jrbCorrente);
        jrbCorrente.setMnemonic('c');
        jrbCorrente.setSelected(true);
        jrbCorrente.setText("Conta Corrente");

        bgContas.add(jrbPoupanca);
        jrbPoupanca.setMnemonic('p');
        jrbPoupanca.setText("Conta Poupança");

        jbConsultar.setMnemonic('s');
        jbConsultar.setText("Consultar");

        jbAtualizar.setMnemonic('a');
        jbAtualizar.setText("Atualizar");
        jbAtualizar.setEnabled(false);

        jbFechar.setMnemonic('f');
        jbFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator01, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAgencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlNome, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jrbCorrente)
                                        .addGap(47, 47, 47)
                                        .addComponent(jrbPoupanca))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(jtfEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfNome)
                                        .addComponent(jtfCpf)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator02)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbConsultar)
                        .addGap(58, 58, 58)
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbFechar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAgencia)
                    .addComponent(jtfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlConta)
                    .addComponent(jtfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator01, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCorrente)
                    .addComponent(jrbPoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator02, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultar)
                    .addComponent(jbAtualizar)
                    .addComponent(jbFechar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarBounds() {
        jlAgencia.setBounds(10, 10, 110, 18);
        jtfAgencia.setBounds(125, 10, 50, 20);
        jlConta.setBounds(205, 10, 105, 18);
        jtfConta.setBounds(315, 10, 60, 20);
        jSeparator01.setBounds(10, 40, 365, 10);
        jlNome.setBounds(10, 50, 60, 18);
        jtfNome.setBounds(75, 50, 300, 20);
        jlEndereco.setBounds(10, 75, 60, 18);
        jtfEndereco.setBounds(75, 75, 300, 20);
        jlTelefone.setBounds(10, 100, 60, 18);
        jtfTelefone.setBounds(75, 100, 300, 20);
        jlCpf.setBounds(10, 125, 60, 18);
        jtfCpf.setBounds(75, 125, 300, 20);
        jrbCorrente.setBounds(100, 150, 111, 20);
        jrbPoupanca.setBounds(225, 150, 118, 20);
        jSeparator02.setBounds(10, 180, 365, 10);
        jbConsultar.setBounds(35, 190, 100, 23);
        jbAtualizar.setBounds(145, 190, 100, 23);
        jbFechar.setBounds(255, 190, 100, 23);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Janela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgContas;
    private javax.swing.JSeparator jSeparator01;
    private javax.swing.JSeparator jSeparator02;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JLabel jlAgencia;
    private javax.swing.JLabel jlConta;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JRadioButton jrbCorrente;
    private javax.swing.JRadioButton jrbPoupanca;
    private javax.swing.JTextField jtfAgencia;
    private javax.swing.JTextField jtfConta;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
