/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ControleDeClientes;

import javax.swing.JOptionPane;

/**
 *
 * @author Caio Moreira Cancela
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Lbl_Img = new javax.swing.JLabel();
        Lbl_Titulo = new javax.swing.JLabel();
        Mn_Principal = new javax.swing.JMenuBar();
        Mn_Arquivo = new javax.swing.JMenu();
        BtnMn_Novo = new javax.swing.JMenuItem();
        BtnMn_Sair = new javax.swing.JMenuItem();
        Mn_Relatorio = new javax.swing.JMenu();
        BtnMn_Clientes = new javax.swing.JMenuItem();
        BtnMn_Fornecedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU, ITENS DE MENU, FONTES");

        Panel.setBackground(new java.awt.Color(255, 255, 102));
        Panel.setPreferredSize(new java.awt.Dimension(600, 400));

        Lbl_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestãoDeAluno/Img/images.png"))); // NOI18N
        Lbl_Img.setText("jLabel1");

        Lbl_Titulo.setFont(new java.awt.Font("Roboto Bk", 1, 24)); // NOI18N
        Lbl_Titulo.setForeground(new java.awt.Color(51, 153, 0));
        Lbl_Titulo.setText("CONTROLE DE CLIENTES");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(Lbl_Titulo)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addComponent(Lbl_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(Lbl_Titulo)
                .addGap(73, 73, 73)
                .addComponent(Lbl_Img)
                .addGap(62, 62, 62))
        );

        Mn_Arquivo.setText("Arquivo");

        BtnMn_Novo.setText("Novo");
        BtnMn_Novo.addActionListener(this::BtnMn_NovoActionPerformed);
        Mn_Arquivo.add(BtnMn_Novo);

        BtnMn_Sair.setText("Sair");
        BtnMn_Sair.addActionListener(this::BtnMn_SairActionPerformed);
        Mn_Arquivo.add(BtnMn_Sair);

        Mn_Principal.add(Mn_Arquivo);

        Mn_Relatorio.setText("Relatorio");

        BtnMn_Clientes.setText("Relatorio de Clientes");
        BtnMn_Clientes.addActionListener(this::BtnMn_ClientesActionPerformed);
        Mn_Relatorio.add(BtnMn_Clientes);

        BtnMn_Fornecedores.setText("Relatorio de Fornecedores");
        BtnMn_Fornecedores.addActionListener(this::BtnMn_FornecedoresActionPerformed);
        Mn_Relatorio.add(BtnMn_Fornecedores);

        Mn_Principal.add(Mn_Relatorio);

        setJMenuBar(Mn_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMn_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnMn_SairActionPerformed

    private void BtnMn_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMn_ClientesActionPerformed
        JOptionPane.showMessageDialog(this,"Relatório de clientes");
    }//GEN-LAST:event_BtnMn_ClientesActionPerformed

    private void BtnMn_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMn_FornecedoresActionPerformed
        JOptionPane.showMessageDialog(this, "Relatório de fornecedores");
    }//GEN-LAST:event_BtnMn_FornecedoresActionPerformed

    private void BtnMn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMn_NovoActionPerformed
        FormCadastroPessoas cadastro = new FormCadastroPessoas(this);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BtnMn_NovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnMn_Clientes;
    private javax.swing.JMenuItem BtnMn_Fornecedores;
    private javax.swing.JMenuItem BtnMn_Novo;
    private javax.swing.JMenuItem BtnMn_Sair;
    private javax.swing.JLabel Lbl_Img;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JMenu Mn_Arquivo;
    private javax.swing.JMenuBar Mn_Principal;
    private javax.swing.JMenu Mn_Relatorio;
    private javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables
}
