/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package  ControleDeClientes;

import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Caio Moreira Cancela
 */
public class FormCadastroPessoas extends javax.swing.JFrame {
   private FormPrincipal formPrincipal;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadastroPessoas.class.getName());

    /**
     * Creates new form FormCadastroPessoas
     * @param form
     */
    public FormCadastroPessoas(FormPrincipal form){
        this.formPrincipal = formPrincipal;
        initComponents();
    }

    public String getBx_Tipo() {
        return Bx_Tipo.getSelectedItem().toString();
    }

    public String getImp_CPF() {
        return Imp_CPF.getText();
    }

    
    public String getImp_Idade() {
        return Imp_Idade.getText();
    }

    public String getImp_Nome() {
        return Imp_Nome.getText();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imp_Nome1 = new javax.swing.JTextField();
        Lbl_Nome2 = new javax.swing.JLabel();
        Imp_Nome3 = new javax.swing.JTextField();
        Imp_CPF1 = new javax.swing.JTextField();
        Lbl_CPF1 = new javax.swing.JLabel();
        Lbl_Nome = new javax.swing.JLabel();
        Imp_Nome = new javax.swing.JTextField();
        Imp_Idade = new javax.swing.JTextField();
        Lbl_Nome1 = new javax.swing.JLabel();
        Lbl_CPF = new javax.swing.JLabel();
        Imp_CPF = new javax.swing.JTextField();
        Lbl_Tipo = new javax.swing.JLabel();
        Bx_Tipo = new javax.swing.JComboBox<>();
        Btn_Cadastrar = new javax.swing.JButton();

        Lbl_Nome2.setText("Idade: ");

        Imp_CPF1.addActionListener(this::Imp_CPF1ActionPerformed);

        Lbl_CPF1.setText("CPF");
        Lbl_CPF1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DE PESSOAS");
        setBackground(new java.awt.Color(255, 255, 0));

        Lbl_Nome.setText("Nome: ");

        Lbl_Nome1.setText("Idade: ");

        Lbl_CPF.setText("CPF");
        Lbl_CPF.setToolTipText("");

        Lbl_Tipo.setText("Tipo:");
        Lbl_Tipo.setToolTipText("");

        Bx_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Fornecedor" }));

        Btn_Cadastrar.setText("CADASTRAR");
        Btn_Cadastrar.addActionListener(this::Btn_CadastrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Nome)
                            .addComponent(Lbl_Nome1)
                            .addComponent(Lbl_CPF)
                            .addComponent(Lbl_Tipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Imp_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(Imp_Idade, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(Imp_Nome)
                            .addComponent(Bx_Tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Btn_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Nome)
                    .addComponent(Imp_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imp_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Nome1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imp_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_CPF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Tipo)
                    .addComponent(Bx_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_Cadastrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CadastrarActionPerformed
        String Texto = "Nome: " + getImp_Nome() +
                "\nIdade: " + getImp_Idade() + 
                "\nCPF: " + getImp_CPF() +
                "\nTipo: " + getBx_Tipo();
        JOptionPane.showMessageDialog(this,"Nome: " + Texto);
        this.dispose();
    }//GEN-LAST:event_Btn_CadastrarActionPerformed

    private void Imp_CPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imp_CPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imp_CPF1ActionPerformed

    public FormCadastroPessoas(JButton Btn_Cadastrar, JComboBox<String> Bx_Tipo, JTextField Imp_CPF, JTextField Imp_CPF1, JTextField Imp_Nome, JTextField Imp_Nome1, JTextField Imp_Nome2, JTextField Imp_Nome3, JLabel Lbl_CPF, JLabel Lbl_CPF1, JLabel Lbl_Nome, JLabel Lbl_Nome1, JLabel Lbl_Nome2, JLabel Lbl_Tipo) throws HeadlessException {
        this.Btn_Cadastrar = Btn_Cadastrar;
        this.Bx_Tipo = Bx_Tipo;
        this.Imp_CPF = Imp_CPF;
        this.Imp_CPF1 = Imp_CPF1;
        this.Imp_Nome = Imp_Nome;
        this.Imp_Nome1 = Imp_Nome1;
        this.Imp_Idade = Imp_Nome2;
        this.Imp_Nome3 = Imp_Nome3;
        this.Lbl_CPF = Lbl_CPF;
        this.Lbl_CPF1 = Lbl_CPF1;
        this.Lbl_Nome = Lbl_Nome;
        this.Lbl_Nome1 = Lbl_Nome1;
        this.Lbl_Nome2 = Lbl_Nome2;
        this.Lbl_Tipo = Lbl_Tipo;
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadastroPessoas().setVisible(true));
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cadastrar;
    private javax.swing.JComboBox<String> Bx_Tipo;
    private javax.swing.JTextField Imp_CPF;
    private javax.swing.JTextField Imp_CPF1;
    private javax.swing.JTextField Imp_Idade;
    private javax.swing.JTextField Imp_Nome;
    private javax.swing.JTextField Imp_Nome1;
    private javax.swing.JTextField Imp_Nome3;
    private javax.swing.JLabel Lbl_CPF;
    private javax.swing.JLabel Lbl_CPF1;
    private javax.swing.JLabel Lbl_Nome;
    private javax.swing.JLabel Lbl_Nome1;
    private javax.swing.JLabel Lbl_Nome2;
    private javax.swing.JLabel Lbl_Tipo;
    // End of variables declaration//GEN-END:variables
}

